version: '3.8'

services:
  database:
    image: postgres:13
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: shop
      POSTGRES_PASSWORD: Start123
      POSTGRES_DB: db1
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/data:/var/lib/postgresql/data


  backend:
    image: homelabhost.de/webshop/backend:0.0.1
    restart: always
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker-test"
    depends_on:
      - database
