version: "3.8"
services:
    frontend:
        env_file: .env
        image: ${REGISTRY}/frontend
        ports:
        - "80:80"
        depends_on:
        - userbackend
        - shopbackend
    userbackend:
        env_file: .env
        image: ${REGISTRY}/userbackend
        ports:
        - "8000:8000"

    redis:
        image: redis
        ports:
        - "6379:6379"

    shopbackend:
        env_file: .env
        image: ${REGISTRY}/shopbackend
        ports:
        - "8080:8080"

