name: flutterfrontend
description: Frontend for Webshop


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: any
  scrollable_positioned_list: ^0.3.5
  vitality: ^1.0.4
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  provider: ^6.0.0
  decimal: ^2.3.2
  url_strategy: ^0.2.0
  shared_preferences: ^2.1.1
  flutter_session_manager: ^1.0.3
  hive:
  hive_flutter:


dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator:
  build_runner:


  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/shopElements/

