server:
  port: 8080

spring:
  profiles:
    active: dev
---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://130.61.188.61:5432/shop
    username: shop
    password: Start123
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
---

spring:
  config:
    activate:
      on-profile: docker-test

  datasource:
    url: jdbc:postgresql://130.61.188.61:5432/shop
    username: shop
    password: Start123
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create

