name: SonarQube analysis

on:
  push:
    branches: [ "dev", main ]
  pull_request:
    branches: [ "dev" ]
  workflow_dispatch:

permissions:
  pull-requests: read 
jobs:
  
  Check-Shop-Backend:
   
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
         distribution: 'adopt'
         java-version: '17'
         
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.2
          
      - name: Set Sonarqube Server Certificate
        shell: bash
        run: |
          echo "${{ secrets.SONAR_ROOT_CERT }}" > sonarcert.pem
          openssl x509 -outform der -in sonarcert.pem -out sonarcert.crt
          keytool -import -noprompt -trustcacerts -alias SonarCube -file sonarcert.crt -keystore $JAVA_HOME/lib/security/cacerts -storepass changeit
          
      - name: SonarQube Scan Shop Backend
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_SHOP_BACKEND }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          cd WebshopBackend
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY_SHOP_BACKEND }}   
          
          
          
  Check-Auth-Backend:
    # The type of runner that the job will run on
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
         distribution: 'adopt'
         java-version: '17'
         
      - name: Set Sonarqube Server Certificate
        shell: bash
        run: |
          echo "${{ secrets.SONAR_ROOT_CERT }}" > sonarcert.pem
          openssl x509 -outform der -in sonarcert.pem -out sonarcert.crt
          keytool -import -noprompt -trustcacerts -alias SonarCube -file sonarcert.crt -keystore $JAVA_HOME/lib/security/cacerts -storepass changeit
          
          
      - name: SonarQube Scan on User/Auth Backend
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_AUTH_BACKEND }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_ROOT_CERT: ${{ secrets.SONAR_ROOT_CERT }}
        with:
          # Additional arguments for the sonarcloud scanner
          args:
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY_AUTH_BACKEND }}
            -Dsonar.sources=src
            -Dsonar.projectBaseDir=./UserAndAuthBackend


  check-frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set Sonarqube Server Certificate
        run: |
          echo "${{ secrets.SONAR_ROOT_CERT }}" > sonarqube.crt
          echo "yes" | sudo keytool -importcert -keystore $JAVA_HOME/lib/security/cacerts -storepass changeit -alias sonarqube -file sonarqube.crt -cacerts
    
      - name: Setup Flutter SDK   
        uses: flutter-actions/setup-flutter@v2
        with:
          channel: stable
          version: 3.10.4
          
    
      - name: Scan Frontend
        run: |
          cd ./WebshopFrontend
          flutter pub get
          docker run --rm \
          -e SONAR_TOKEN=${{ secrets.SONAR_TOKEN_FRONTEND }} \
          -e SONAR_HOST_URL=${{ secrets.SONAR_HOST_URL }} \
          -v $(pwd):/usr/src \
          -w /usr/src \
          -v $JAVA_HOME/lib/security/cacerts:/usr/lib/jvm/default-jvm/lib/security/cacerts \
          sonarsource/sonar-scanner-cli:latest \
          -Djavax.net.ssl.trustStore=/usr/lib/jvm/default-jvm/lib/security/cacerts \
          -Djavax.net.ssl.trustStorePassword=changeit \
          -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY_FRONTEND }} \
          -Dsonar.sources=lib \
          -Dsonar.exclusions="**/*.g.dart"
 





            
        

